export { default as DashboardPage } from "./dashboard/DashboardPage"
export { default as OrdersPage } from "./orders/OrdersPage"
export { default as RestaurantDetailsPage } from "./restaurant/RestaurantDetailsPage"
export { default as CategoriesPage } from "./menu/CategoriesPage"
export { default as ProductsPage } from "./menu/ProductsPage"
export { default as TablesPage } from "./tables/TablesPage"